baseURL = "https://feminizidmap.org/"
languageCode = "en-us"
theme = "feminicide-theme"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Feminizidmap.org"
    languageName = "English"
    weight = 1
  [languages.de]
    title = "Feminizidmap.org"
    languageName = "Deutsch"
    weight = 2
    [languages.de.params.navigation]
      project = "Das Project"
      publications = "Veröffentlichungen"
      data = "Daten"

[params]
  [params.navigation]
    project = "The Project"
    publications = "Publications"
    data = "Data"
