baseURL = "https://feminizidmap.org/"
languageCode = "en-us"
theme = "feminicide-theme"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Feminizidmap.org"
    languageName = "English"
    weight = 1
  [languages.de]
    title = "Feminizidmap.org"
    languageName = "Deutsche"
    weight = 2

[params]
  [params.navigation]
    about = "/about"
    faq = "/faq"
    researchers = "/researchers"
    contributions = "/contributions"
  [params.secondary]
    imprint = "/imprint"
