baseURL = "https://feminizidmap.org/"
languageCode = "en-us"
theme = "feminicide-theme"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Feminizidmap.org"
    languageName = "English"
    weight = 1
  [languages.de]
    title = "Feminizidmap.org"
    languageName = "Deutsche"
    weight = 2
    [languages.de.params.navigation]
      about = "Über"
      researchers = "Forscher:innen"
      faq = "FAQ"
    [languages.de.params.secondary]
      imprint = "Impressum"

[params]
  [params.navigation]
    about = "About"
    researchers = "Researchers"
    faq = "FAQ"
  [params.secondary]
    imprint = "Imprint"
